CCOMPILE = "/work/toolchain_R2_EABI/usr/bin/arm-none-linux-gnueabi-gcc"
CPPCOMPILE = "/work/toolchain_R2_EABI/usr/bin/arm-none-linux-gnueabi-g++"
STRIP = "/work/toolchain_R2_EABI/usr/bin/arm-none-linux-gnueabi-strip"
LINK = "/work/toolchain_R2_EABI/usr/bin/arm-none-linux-gnueabi-g++"
VER = release
#VER = debug

ifeq ($(VER), debug)
CFG_DEBUG = -g3
else
CFG_DEBUG = -O2 -DNDEBUG
endif

#CFG_CFLGS = -Wall
CFG_CFLGS = 
